const samplesArray = [
  {
    brand: "Ginger",
    color: "Crystal Black 1015",
    price: { uah: 0, eur: 0, usd: 375 },
    slab: [3030, 1430],
    colorGroup: ["black"],
    pattern: ["sparkle"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/CT-401.jpg",
  },
  {
    brand: "Ginger",
    color: "Cararra White 6305",
    price: { uah: 0, eur: 0, usd: 485 },
    slab: [3030, 1430],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Ginger/Cararra-White-6305.jpg",
  },
  {
    brand: "Ginger",
    color: "Calacatta White 7412",
    price: { uah: 0, eur: 0, usd: 700 },
    slab: [3030, 1430],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Ginger/Calacatta-White-7412.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco City",
    price: { uah: 0, eur: 655, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["beige"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Blanco-City.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco City",
    price: { uah: 0, eur: 753, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["beige"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Blanco-City.jpg",
  },
  {
    brand: "Silestone",
    color: "Gris Expo",
    price: { uah: 0, eur: 655, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/Gris-Expo.jpg",
  },
  {
    brand: "Silestone",
    color: "Gris Expo",
    price: { uah: 0, eur: 753, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/Gris-Expo.jpg",
  },
  {
    brand: "Silestone",
    color: "Gris Expo",
    price: { uah: 0, eur: 753, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "volcano",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/Gris-Expo.jpg",
  },
  {
    brand: "Silestone",
    color: "Marengo",
    price: { uah: 0, eur: 655, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/MAR-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Marengo",
    price: { uah: 0, eur: 753, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/MAR-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Noka",
    price: { uah: 0, eur: 655, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["brown"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Noka.jpg",
  },
  {
    brand: "Silestone",
    color: "Noka",
    price: { uah: 0, eur: 753, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["brown"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Noka.jpg",
  },
  {
    brand: "Silestone",
    color: "Rougui",
    price: { uah: 0, eur: 655, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["brown"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/Rougui.jpg",
  },
  {
    brand: "Silestone",
    color: "Rougui",
    price: { uah: 0, eur: 753, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["brown"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/Rougui.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Maple 14",
    price: { uah: 0, eur: 770, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/M14-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Maple 14",
    price: { uah: 0, eur: 886, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/M14-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Norte 14",
    price: { uah: 0, eur: 770, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BN1-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Norte 14",
    price: { uah: 0, eur: 886, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BN1-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Cemento Spa",
    price: { uah: 0, eur: 770, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/CV-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Cemento Spa",
    price: { uah: 0, eur: 886, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/CV-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Cemento Spa",
    price: { uah: 0, eur: 886, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "volcano",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/CV-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Miami White 17",
    price: { uah: 0, eur: 770, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/MW7-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Negro Tebas 18",
    price: { uah: 0, eur: 770, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["black"],
    pattern: ["zerno", "manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/GV3-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Negro Tebas 18",
    price: { uah: 0, eur: 886, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["black"],
    pattern: ["zerno", "manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/GV3-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Aluminio Nube ",
    price: { uah: 0, eur: 835, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/5N-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Aluminio Nube ",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/5N-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Amazon",
    price: { uah: 0, eur: 835, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["brown"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "out",
    picture: "./images/samples/Silestone/silestone-gris-amazon-big-min.jpg",
  },
  {
    brand: "Silestone",
    color: "Amazon",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["brown"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "out",
    picture: "./images/samples/Silestone/silestone-gris-amazon-big-min.jpg",
  },
  {
    brand: "Silestone",
    color: "Amazon",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["brown"],
    pattern: ["manka"],
    surface: "volcano",
    recommend: "",
    preorder: "",
    out: "out",
    picture: "./images/samples/Silestone/silestone-gris-amazon-big-min.jpg",
  },
  {
    brand: "Silestone",
    color: "Bianco Rivers",
    price: { uah: 0, eur: 835, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white", "grey"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BD-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Bianco Rivers",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white", "grey"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BD-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Bianco Rivers",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white", "grey"],
    pattern: ["marble"],
    surface: "volcano",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BD-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Stellar 13",
    price: { uah: 0, eur: 835, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["zerno"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BS4-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Stellar 13",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["zerno"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BS4-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Cygnus 15 ",
    price: { uah: 0, eur: 835, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/VC5-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Cygnus 15 ",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/VC5-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Negro Stellar",
    price: { uah: 0, eur: 835, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["black"],
    pattern: ["sparkle"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/ES-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Tigris Sand",
    price: { uah: 0, eur: 835, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["beige"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/6T-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Tigris Sand",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["beige"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/6T-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Tigris Sand",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["beige"],
    pattern: ["marble"],
    surface: "volcano",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/6T-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "White Storm 14",
    price: { uah: 0, eur: 835, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/WS1-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "White Storm 14",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/WS1-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Yukon ",
    price: { uah: 0, eur: 835, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["marble", "manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/6Y-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Yukon ",
    price: { uah: 0, eur: 960, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["marble", "manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/6Y-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Arden Blue",
    price: { uah: 0, eur: 931, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["zerno"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/ARU-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Arden Blue",
    price: { uah: 0, eur: 1071, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["zerno"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/ARU-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Arden Blue",
    price: { uah: 0, eur: 1071, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["zerno"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/ARU-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Coral Clay",
    price: { uah: 0, eur: 931, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BCR-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Coral Clay",
    price: { uah: 0, eur: 1071, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BCR-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Ironbark",
    price: { uah: 0, eur: 931, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/SBR-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Ironbark",
    price: { uah: 0, eur: 1071, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/SBR-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Niebla",
    price: { uah: 0, eur: 931, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/NIE-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Niebla",
    price: { uah: 0, eur: 1071, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/NIE-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Pulsar",
    price: { uah: 0, eur: 931, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/ISM-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Pulsar",
    price: { uah: 0, eur: 1071, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/ISM-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Royal Reef ",
    price: { uah: 0, eur: 931, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige", "brown"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/SL3-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Royal Reef ",
    price: { uah: 0, eur: 1071, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige", "brown"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/SL3-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Alpina White 08 ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/6B-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Alpina White 08 ",
    price: { uah: 0, eur: 1159, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/6B-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Capri",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/EW-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Capri",
    price: { uah: 0, eur: 1159, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/EW-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Classic White ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/VZ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Classic White ",
    price: { uah: 0, eur: 1159, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/VZ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Desert Silver ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble", "calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/GVX-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Desert Silver ",
    price: { uah: 0, eur: 1159, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble", "calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/GVX-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Kimbler Mist ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/SL9-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Miami Vena ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/MVN-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Miami Vena ",
    price: { uah: 0, eur: 1159, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/MVN-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Mountain Mist 12 ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble", "zerno"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/MOM-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Mountain Mist 12 ",
    price: { uah: 0, eur: 1159, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble", "zerno"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/MOM-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Sienna Ridge 12 ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["zerno"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/MOS-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Silken Pearl ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Silken-Pearl.jpg",
  },
  {
    brand: "Silestone",
    color: "Silken Pearl ",
    price: { uah: 0, eur: 1159, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Silken-Pearl.jpg",
  },
  {
    brand: "Silestone",
    color: "Snow Ibiza ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/LG1-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Snow Ibiza ",
    price: { uah: 0, eur: 1159, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/LG1-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "White Arabesque ",
    price: { uah: 0, eur: 1008, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/LG2-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "White Arabesque ",
    price: { uah: 0, eur: 1159, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/LG2-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Camden",
    price: { uah: 0, eur: 1070, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Camden.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Orion ",
    price: { uah: 0, eur: 1079, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/BON-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Blanco Orion ",
    price: { uah: 0, eur: 1241, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/BON-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "BlancoZeus",
    price: { uah: 0, eur: 1079, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/BZ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "BlancoZeus",
    price: { uah: 0, eur: 1241, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/BZ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "BlancoZeus",
    price: { uah: 0, eur: 1241, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "volcano",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/BZ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Lagoon ",
    price: { uah: 0, eur: 1079, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/VLN-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Lagoon ",
    price: { uah: 0, eur: 1241, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/VLN-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Lyra ",
    price: { uah: 0, eur: 1079, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/VLM-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Lyra ",
    price: { uah: 0, eur: 1241, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/VLM-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Merope ",
    price: { uah: 0, eur: 1079, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["brown"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/VMN-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Merope ",
    price: { uah: 0, eur: 1241, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["brown"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/VMN-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Stellar Grey ",
    price: { uah: 0, eur: 1079, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["zerno"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/STJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Stellar Grey ",
    price: { uah: 0, eur: 1241, usd: 0 },
    slab: [3060, 1400],
    colorGroup: ["grey"],
    pattern: ["zerno"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/STJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Bamboo 08 ",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige", "brown"],
    pattern: ["zerno"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/XB-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Charcoal Soapstone",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/1JH-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Charcoal Soapstone",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/1JH-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Copper Mist",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/ICM-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Serena",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/1JS-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Serena",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/1JS-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Haiku",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "out",
    picture: "./images/samples/Silestone/silestone-zen-05-haiku-h.jpg",
  },
  {
    brand: "Silestone",
    color: "Haiku",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "out",
    picture: "./images/samples/Silestone/silestone-zen-05-haiku-h.jpg",
  },
  {
    brand: "Silestone",
    color: "Helix ",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey", "white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/HAS-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Helix ",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey", "white"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/HAS-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Iconic Black",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/SL6-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Kensho ",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/ZQ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Kensho ",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/ZQ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Kensho ",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["manka"],
    surface: "volcano",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/ZQ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Lusso ",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige", "grey"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "out",
    picture: "./images/samples/Silestone/LSS-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Pearl Jasmine ",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble", "calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/1JP-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Pearl Jasmine ",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble", "calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/1JP-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Unsui ",
    price: { uah: 0, eur: 1303, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/ZZ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Unsui ",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/ZZ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Ariel ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/ARI-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Ariel ",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/ARI-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Calypso ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/CAY-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Calypso ",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/CAY-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Classic Calacatta ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "out",
    picture: "./images/samples/Silestone/1JR-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Classic Calacatta ",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "out",
    picture: "./images/samples/Silestone/1JR-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Bella ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/NWH-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Bella ",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/NWH-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal D`or ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/NMB-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal D`or ",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/NMB-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Emperador ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble", "calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/EPJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Emperador ",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["brown"],
    pattern: ["marble", "calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/EPJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Marfil ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/ECJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Marfil ",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["beige"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/ECJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Marquina",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/1JM-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Marquina",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/1JM-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Statuario",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble", "calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/1JE-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Statuario",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble", "calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/1JE-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Iconic White ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BJJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Iconic White ",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["manka"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BJJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Ocean Jasper ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/OJF-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Ocean Storm ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/OCA-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Pacifica ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/OCP-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Pietra ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/SL8-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Pietra ",
    price: { uah: 0, eur: 1665, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/SL8-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "White Diamond ",
    price: { uah: 0, eur: 1448, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["zerno"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/WD2-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Corktown ",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Corktown.jpg",
  },
  {
    brand: "Silestone",
    color: "Nolita ",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/HCT-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Poblenou ",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/C10-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Seaport ",
    price: { uah: 0, eur: 1498, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/GCT-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Bianco Calacatta ",
    price: { uah: 0, eur: 1758, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BCT-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Bianco Calacatta ",
    price: { uah: 0, eur: 2022, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "",
    out: "",
    picture: "./images/samples/Silestone/BCT-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Calacatta Gold",
    price: { uah: 0, eur: 1758, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Eternal-Calacatta-Gold.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Calacatta Gold",
    price: { uah: 0, eur: 2022, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["white"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/Eternal-Calacatta-Gold.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Noir ",
    price: { uah: 0, eur: 1758, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/SNJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Eternal Noir ",
    price: { uah: 0, eur: 2022, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["black"],
    pattern: ["calacatta"],
    surface: "suede",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/SNJ-detail.jpg",
  },
  {
    brand: "Silestone",
    color: "Polaris ",
    price: { uah: 0, eur: 1758, usd: 0 },
    slab: [3250, 1590],
    colorGroup: ["grey"],
    pattern: ["marble", "calacatta"],
    surface: "glanz",
    recommend: "",
    preorder: "preorder",
    out: "",
    picture: "./images/samples/Silestone/TMH-detail.jpg",
  },
];
